[Match]
Distribution=ubuntu

[Content]
CleanPackageMetadata=true
Packages=linux-image-generic
         dmsetup
KernelModulesInitrdInclude=default
KernelModulesInitrdInclude=dm-mod
KernelModulesInitrdInclude=dm-verity
RemoveFiles=/var/cache/ldconfig/aux-cache
